### ISSUE TITLE
What is this repo for?

### ISSUE THREAD

**Issue by lbmeng** [starfive-tech/beagle_secondBoot#2]
I don't understand what is this repo for. The readme.txt only provides some vague instructions related to build process.

Is this repo containing the source codes of the on-chip boot ROM?

**Comment by pdp7** [comment]
The is the program that the boot ROM jumps to on the SPI flash.

Bootflow is:
1. ROM in SoC (zero stage)
2. SPI Flash: first stage bootloader which StarFive calls "second boot"
3. SPI Flash: DDR init bootloader
4. SPI Flash: OpenSBI + u-boot

**Comment by lbmeng** [comment]
Thanks.

Unforunately this bootflow does not fit well with current U-Boot on RISC-V.
We will need to figure out a proper way when doing upstreaming U-Boot support.

**Comment by pdp7** [comment]
@davidlt had been talking to me about how SiFive U540 is now using u-boot SPL.  I think it would be great to do that as well for StarFive.  Then u-boot SPL could maybe replace "second boot" and DDR init.  What do you think would be needed in order for that to work?

**Comment by lbmeng** [comment]
That's my original plan as well - using U-Boot SPL to replace "second boot" and "DDRinit".

However I will need more information on the documentation regarding to:

1. Details on how the on-chip boot ROM loads the 2nd boot and where the 2nd boot runs
2. A way to test the updated bootloader image (question posted on BeagleV forum [here](https://forum.beagleboard.org/t/system-boot-sequence/29361))

**Comment by pdp7** [comment]
@lbmeng thank you for describing what you need.  I will raise this in my weekly meeting with the StarFive software team tomorrow.

**Comment by pdp7** [comment]
@lbmeng fyi -  [Update bootloader, ddr init boot, u-boot and Recover bootloader](https://wiki.seeedstudio.com/BeagleV-Update-bootloader-ddr-init-boot-uboot-Recover-bootloader/)
