### ISSUE TITLE
File bigger than 3MB not supported

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_secondBoot#4]
From Daniel Schafer:
With picocom I see this error.
My file is 8MB but picocom fails because the limit is 3M?
![image-3](https://user-images.githubusercontent.com/313864/117227256-4145ec80-adcb-11eb-9505-5c0bd6cc150f.png)

**Comment by JohnAZoidberg** [comment]
With minicom I see this:

![image](https://user-images.githubusercontent.com/5307138/117255380-28494400-ae7c-11eb-9bcb-a3877826376e.png)

Flashing seems to work but when I quit the bootloader it boots into U-Boot again.

**Comment by JohnAZoidberg** [comment]
Context: I'm trying to flash a build of EDK2, which generates an 8MB image.
After flashing I would expect U-Boot to be gone.

**Comment by MichaelZhuxx** [comment]
common/sys.h

**Comment by MichaelZhuxx** [comment]
I have expanded the limit to 10MB, you can update it.
[](url)https://github.com/starfive-tech/beagle_ddrlnit/commit/623888127a0e6b38d4c1839297286662b570dfa6

**Comment by pdp7** [comment]
@tekkamanninja @JohnAZoidberg please try this fix

**Comment by pdp7** [comment]
@MichaelZhuxx is there a reason to not have the limit by 32MB which is size of the flash chip?

**Comment by JohnAZoidberg** [comment]
I need to build this myself?
Could you please provide a binary that I can directly flash? :)

**Comment by MichaelZhuxx** [comment]
Daniel,

Please update the attached ddrinit binary and let me know the results. Thanks.

发件人: Daniel Schaefer ***@***.***>
答复: starfive-tech/beagle_secondBoot ***@***.***>
日期: 2021年5月7日 星期五 下午2:10
收件人: starfive-tech/beagle_secondBoot ***@***.***>
抄送: Michael Zhu ***@***.***>, Mention ***@***.***>
主题: Re: [starfive-tech/beagle_secondBoot] File bigger than 3MB not supported (#4)


I need to build this myself?
Could you please provide a binary that I can directly flash? :)

**Comment by pdp7** [comment]
@MichaelZhuxx was there supposed to be a file attached?  It seems it did not make it

**Comment by JohnAZoidberg** [comment]
![image](https://user-images.githubusercontent.com/5307138/117425119-c7287b80-af22-11eb-863c-3976ad2e53c3.png)
Flashing worked, thanks!

No output after secondboot anymore but that's probably my code's issue.

**Comment by pdp7** [comment]
@JohnAZoidberg please re-open if further problems
