### ISSUE TITLE
Add  SPDX-License-Identifer

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_secondBoot#6]
@MichaelZhuxx  `SPDX-License-Identifier: GPL-2.0-or-later` should be added to these source code files that StarFive owns the copyright on

**Comment by MichaelZhuxx** [comment]
@pdp7 Please check it https://github.com/starfive-tech/beagle_secondBoot/commit/048f63f3e8449bae9ed8525bf7c204e1e98e1957

**Comment by pdp7** [comment]
@MichaelZhuxx thank you for adding those SPDX headers.

I also have created a LICENSE file.  Please review PR https://github.com/starfive-tech/beagle_secondBoot/pull/7
