### ISSUE TITLE
Clear 0x7c1 CSR

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/beagle_secondBoot#8]
Now that the BeagleV Starlight board is moving to OpenSBI generic platform, we need to [clear 0x7c1 CSR](https://github.com/davidlt/opensbi/commit/7e1952c73e4cc2172e98f6cd4da568d829a3291f) in secondboot or ddrinit while still in m-mode.  This improves the performance of the SiFive U74 cores

**Comment by pdp7** [comment]
cc @atishp04 @davidlt @lbmeng

**Comment by MichaelZhuxx** [comment]
@pdp7 please check this commit https://github.com/starfive-tech/beagle_secondBoot/commit/f5b3e894a2a9a4c13d087d3210a694285a803eb0

**Comment by pdp7** [comment]
> @pdp7 please check this commit [f5b3e89](https://github.com/starfive-tech/beagle_secondBoot/commit/f5b3e894a2a9a4c13d087d3210a694285a803eb0)

@MichaelZhuxx thank you

@davidlt does that look correct to you?

**Comment by davidlt** [comment]
Yup, should work. I can recheck benchmark once a new SPI Flash image is available.

**Comment by pdp7** [comment]
@davidlt here is the binary that I built and flash ok
[bootloader-BEAGLEV-buildroot.zip](https://github.com/starfive-tech/beagle_secondBoot/files/6629633/bootloader-BEAGLEV-buildroot.zip)

**Comment by pdp7** [comment]
@davidlt did you get to do the benchmark yet?

**Comment by davidlt** [comment]
no yet, do we have instructions how to flash it? I kinda forgot that it's not u-boot so probably not via a menu.

**Comment by davidlt** [comment]
seems the debug header is missing and I need to solder it on for recover to work.

**Comment by MichaelZhuxx** [comment]
> no yet, do we have instructions how to flash it? I kinda forgot that it's not u-boot so probably not via a menu.

@davidlt please refer to this guideline https://wiki.seeedstudio.com/BeagleV-Update-bootloader-ddr-init-boot-uboot-Recover-bootloader/ 
![image](https://user-images.githubusercontent.com/78013124/122326393-d279b880-cf5e-11eb-8954-6c0e2914a44f.png)

**Comment by MichaelZhuxx** [comment]
> seems the debug header is missing and I need to solder it on for recover to work.

you can update the secondboot binary over 40pin header not debug header

**Comment by davidlt** [comment]
I used U-Boot built by Akira which has L2 fully enabled. Did a few runs, coremark is consistently  at 5.13+. LGTM.
